apiVersion: v1
kind: Service
metadata:
  name: filesender-fpm
  namespace: filesender
  labels:
    tier: backend
spec:
  selector:
    app: filesender
    tier: backend
  ports:
    - protocol: TCP
      port: 9000 
